# Generated by Django 6.0.6 on 2026-07-02 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_type', models.CharField(choices=[('Poultry', 'Poultry Sector'), ('Aqua', 'Aqua Sector'), ('General', 'General Agriculture')], default='General', max_length=50)),
                ('chicks_count', models.IntegerField(default=0, verbose_name='Chicks Population')),
                ('grower_count', models.IntegerField(default=0, verbose_name='Grower Population')),
                ('layer_count', models.IntegerField(default=0, verbose_name='Layer Population')),
                ('culling_bird_count', models.IntegerField(default=0, verbose_name='Culling Bird Population')),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(default='State', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(blank=True, default='', help_text='Block or Assigned Area', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executive', models.ForeignKey(blank=True, help_text='The field executive assigned to manage this farm account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_problem', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True, help_text='Date the visit occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_visit_reports', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm_core.farm')),
            ],
            options={
                'verbose_name': 'Field Visit Report',
                'verbose_name_plural': 'Field Visit Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitedProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('potential_quantity', models.IntegerField(blank=True, default=0)),
                ('target_quantity', models.IntegerField(blank=True, default=0)),
                ('sale_quantity', models.IntegerField(default=0)),
                ('unit_type', models.CharField(default='KG', help_text='Bags, Liters, KG etc.', max_length=50)),
                ('primary_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('process_status', models.CharField(choices=[('Cold', '❄️ Cold'), ('Warm', '🔥 Warm'), ('Hot', '💥 Hot')], default='Warm', max_length=50)),
                ('conversion_percentage', models.IntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm_core.farmvisitreport')),
            ],
            options={
                'verbose_name': 'Visited Product Detail',
                'verbose_name_plural': 'Visited Product Details',
            },
        ),
    ]
