# Generated by Django 6.0.7 on 2026-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='sub_segment',
            field=models.CharField(blank=True, help_text='Specific operational sub-classification or industry segment.', max_length=100, null=True),
        ),
    ]
