# Generated by Django 6.0.7 on 2026-07-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0002_farm_sub_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedproductdetail',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_products', to='crm_core.farmvisitreport'),
        ),
    ]
