# Generated by Django 6.0.6 on 2026-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0003_alter_visitedproductdetail_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmvisitreport',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
