# Generated by Django 6.0.6 on 2026-08-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0004_farmvisitreport_next_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmvisitreport',
            name='next_visit_date',
            field=models.DateField(blank=True, help_text='Planned follow-up date captured on the visit-logging form.', null=True),
        ),
    ]
