# Generated by Django 6.0.6 on 2026-08-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0005_alter_farmvisitreport_next_visit_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('whatsapp_group_title', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Group',
                'verbose_name_plural': 'WhatsApp Groups',
            },
        ),
        migrations.CreateModel(
            name='SalesExecutiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executives', to='crm_core.whatsappgroup')),
            ],
            options={
                'verbose_name': 'Sales Executive Profile',
                'verbose_name_plural': 'Sales Executive Profiles',
            },
        ),
    ]
