# Generated by Django 6.0.6 on 2026-08-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0006_whatsappgroup_salesexecutiveprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmvisitreport',
            name='visit_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Follow-up Required', 'Follow-up Required'), ('No Response', 'No Response')], default='Completed', help_text='Outcome status of this visit.', max_length=50),
        ),
    ]
