# Generated by Django 6.0.6 on 2026-08-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0007_farmvisitreport_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='distributor_name',
            field=models.CharField(blank=True, default='', help_text='Distributor associated with this farm account.', max_length=255),
        ),
    ]
