# Generated by Django 6.0.6 on 2026-08-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0009_fix_distributor_name_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='fish_variety',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Fish/Shrimp Variety'),
        ),
        migrations.AddField(
            model_name='farm',
            name='pond_acre',
            field=models.FloatField(default=0.0, verbose_name='Pond Size (Acres)'),
        ),
        migrations.AddField(
            model_name='farm',
            name='pond_doc',
            field=models.IntegerField(default=0, verbose_name='Days of Culture (DOC)'),
        ),
    ]
