# Generated by Django 6.0.6 on 2026-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0010_farm_fish_variety_farm_pond_acre_farm_pond_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmvisitreport',
            name='farm_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
