"""
Django settings for crm_project project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import sys
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-yi(fw7m(n=3e%i%+m4%00imcyq8*uf(_0p)_u9pyxtmk*a3i_5')

# SECURITY WARNING: don't run with debug turned on in production!
# Automatically set DEBUG to False in Render production, True locally
DEBUG = os.environ.get('RENDER', 'False') == 'False'

# 🚀 ALLOWED NETWORK INTERFACES & TUNNELS
ALLOWED_HOSTS = [
    '*', 
    'localhost', 
    '127.0.0.1', 
    '0.0.0.0', 
    'crm.myagrinutritioncrm.com',
    'myagrinutrition-crm.onrender.com'
]

# 🔒 CSRF TRUSTED ORIGINS 
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.trycloudflare.com',       
    'https://trycloudflare.com',          
    'https://crm.myagrinutritioncrm.com',
    'https://myagrinutrition-crm.onrender.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 🔒 Two-Factor Authenticator & OTP Security Extensions
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',  
    'two_factor',
    
    # Register local app modules here:
    'accounts',
    'crm_core',
    
    # 📱 Progressive Web App Engine Module Registration
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 🚀 Serves static assets seamlessly
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # 🔒 OTP Security Middleware
    'django_otp.middleware.OTPMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_project.urls'

# 🛠️ GLOBAL TEMPLATE CONFIGURATION MATRIX
TEMPLATES = [
    {
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==========================================
# 🗄️ PERSISTENT ENGINE DATABASE MATRIX
# ==========================================
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # 🌐 Render Production Database Setup
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True  # 🔒 Render PostgreSQL requires SSL in production!
        )
    }
else:
    # 💻 Local Development Database Setup (Fixes "Connection Refused" Errors)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ==========================================
# 🔓 EASY PASSWORD VALIDATION OVERRIDE
# ==========================================
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# Disable default password restrictions to allow easy passwords:
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # 🌍 Matches regional operational telemetry
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 📂 WhiteNoise Production Resiliency Layout
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Tell Django to use our custom user model globally
AUTH_USER_MODEL = 'accounts.CustomUser'


# ==========================================
# 🔐 SECURE AUTHENTICATION REDIRECT SETTINGS
# ==========================================
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = '/crm/dashboard/'
LOGOUT_REDIRECT_URL = 'two_factor:login'


# ==========================================
# 📱 PROGRESSIVE WEB APP (PWA) ENGINE CONFIGS
# ==========================================
PWA_APP_NAME = 'MY AGRINUTRITION'
PWA_APP_DESCRIPTION = "Live Management Performance & Pipeline Telemetry"
PWA_APP_THEME_COLOR = '#0f172a'    
PWA_APP_BACKGROUND_COLOR = '#0f172a'   
PWA_APP_DISPLAY = 'standalone'         
PWA_APP_ORIENTATION = 'any'            
PWA_APP_START_URL = '/crm/dashboard/'   
PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [
    {
        'src': '/static/images/icon-192.png', 
        'sizes': '192x192'
    },
    {
        'src': '/static/images/icon-512.png', 
        'sizes': '512x512'
    }
]


# ==========================================
# ✉️ COMMUNICATIONS & TELEMETRY DISPATCHERS
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
