"""
Django settings for crm_project project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yi(fw7m(n=3e%i%+m4%00imcyq8*uf(_0p)_u9pyxtmk*a3i_5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 🚀 ALLOWED NETWORK INTERFACES & TUNNELS
ALLOWED_HOSTS = [
    '*', 
    'localhost', 
    '127.0.0.1', 
    '0.0.0.0', 
    'crm.myagrinutritioncrm.com',
    'myagrinutrition-crm.onrender.com'
]

# 🔒 CSRF TRUSTED ORIGINS 
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'https://*.trycloudflare.com',       
    'https://trycloudflare.com',         
    'https://crm.myagrinutritioncrm.com',
    'https://myagrinutrition-crm.onrender.com'  # 🚀 Added Render URL
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 🔒 Two-Factor Authenticator & OTP Security Extensions
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',  
    'two_factor',
    
    # Register local app modules here:
    'accounts',
    'crm_core',
    
    # 📱 Progressive Web App Engine Module Registration
    'pwa',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 🚀 Added WhiteNoise to serve static assets
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # 🔒 OTP Security Middleware
    'django_otp.middleware.OTPMiddleware',
    
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_project.urls'

# 🛠️ GLOBAL TEMPLATE CONFIGURATION
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 🚀 Tells Django where to collect production static files

# Tell Django to use our custom user model globally
AUTH_USER_MODEL = 'accounts.CustomUser'


# ==========================================
# 🔐 SECURE AUTHENTICATION REDIRECT SETTINGS
# ==========================================
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = '/crm/dashboard/'
LOGOUT_REDIRECT_URL = 'two_factor:login'


# ==========================================
# 📱 PROGRESSIVE WEB APP (PWA) ENGINE CONFIGS
# ==========================================
PWA_APP_NAME = 'MY AGRINUTRITION'
PWA_APP_DESCRIPTION = "Live Management Performance & Pipeline Telemetry"
PWA_APP_THEME_COLOR = '#0f172a'    
PWA_APP_BACKGROUND_COLOR = '#0f172a'   
PWA_APP_DISPLAY = 'standalone'         
PWA_APP_ORIENTATION = 'any'            
PWA_APP_START_URL = '/crm/dashboard/'   
PWA_APP_STATUS_BAR_COLOR = 'default'

PWA_APP_ICONS = [
    {
        'src': '/static/images/icon-192.png', 
        'sizes': '192x192'
    },
    {
        'src': '/static/images/icon-512.png', 
        'sizes': '512x512'
    }
]
